version: "3"
services:
  db:
    image: mysql
    ports:
      - 3306:3306
    container_name: db
    env_file:
      - .env
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql-data:/data/db
  api:
    build: .
    links:
      - db
    ports:
      - 5000:5000
    container_name: api-server
    env_file:
      - .env
    entrypoint:
      - dockerize
      - -timeout
      - 60s
      - -wait
      - tcp://db:3306
    command: sh -c "/migrator && /api"
volumes:
  mysql-data:
    driver: local
