FROM golang:latest as builder

ENV CGO_ENABLED=0
ENV GOOS=linux
ENV GOARCH=amd64
WORKDIR /go/src/github.com/uzimaru0000/garbage/worker
COPY . .
RUN make

FROM alpine
RUN apk add --no-cache ca-certificates &&\
    apk add --no-cache mysql-client
COPY --from=builder /go/src/github.com/uzimaru0000/garbage/worker/worker /worker
COPY wait.sh /wait.sh