FROM golang:latest as builder

ENV CGO_ENABLED=0
ENV GOOS=linux
ENV GOARCH=amd64
WORKDIR /go/src/github.com/uzimaru0000/aizu-garbage/api
COPY . .
RUN make

FROM alpine
RUN apk add --no-cache ca-certificates
COPY --from=builder /go/src/github.com/uzimaru0000/aizu-garbage/api/api /api
ENTRYPOINT [ "./api" ]